Repository Project-HAMi/HAMi-core, pull requests merged in 2025-09, with the labels that each got.

#106 feat: Add cuMemcpy2D memory func hook
  src/cuda/hook.c
  src/cuda/memory.c
  src/include/libcuda_hook.h
  src/libvgpu.c
Labels: size/XS, dco-signoff: yes, lgtm, approved

#121 refactor: replace magic number with `CUDA_DEVICE_MAX_COUNT` macro
  src/multiprocess/multiprocess_memory_limit.c
  src/multiprocess/multiprocess_utilization_watcher.c
  src/nvml/hook.c
  src/utils.c
Labels: dco-signoff: yes, size/M, lgtm, approved

#124 fix: check memory null
  src/nvml/hook.c
Labels: dco-signoff: yes, size/S, lgtm, approved
