Repository Project-HAMi/HAMi-core, pull requests merged in 2025-08, with the labels that each got.

#107 fix: fix type incompatibility warnings and unused variables
  src/cuda/hook.c
  src/multiprocess/multiprocess_memory_limit.c
  src/nvml/hook.c
  src/utils.c
Labels: dco-signoff: yes, size/S, lgtm

#108 Fix memory = 0 for some tasks
  OWNERS.md
  src/allocator/allocator.c
  src/multiprocess/multiprocess_memory_limit.c
  src/multiprocess/multiprocess_memory_limit.h
Labels: dco-signoff: yes, size/M

#109 fix:Fix compiler warnings for better code quality
  src/include/cuda_addition_func.h
  src/multiprocess/multiprocess_memory_limit.c
  src/multiprocess/multiprocess_memory_limit.h
  src/nvml/hook.c
  src/nvml/nvml_entry.c
Labels: dco-signoff: yes, size/M, lgtm

#113 refactor:cuda_addition_func.h.unused
  src/cuda/device.c
  src/include/cuda_addition_func.h.unused
  src/libvgpu.c
Labels: size/XS, dco-signoff: yes, lgtm

#118 Fix cuMallocAsync not released properly
  OWNERS
  src/allocator/allocator.c
Labels: dco-signoff: yes, size/S
